# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9236b16939f472aea3bb8d255ce5a7fd253a01c220431b3d9409906097afddb1c50d3b196cf59f0c37c118f0d566514252d0ef65cf6455a246252a8435022cc0

test:
  secret_key_base: a1b046b07ebee3dbe2284b0bd12f8b661b666b775fe1168b4839384a6ce9810737f170ee3b837a43ba64d2acffd5005cfe280e2529753824fdf9a2cd3d12584a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
